#! /bin/sh

##  generic bootstrap file for libraries -- Sam Hocevar <sam@zoy.org>
##  $Id$

set -x
set -e

# Get a sane environment, just in case
LANG=C
export LANG
CYGWIN=binmode
export CYGWIN

# Check for automake
amvers="no"
for v in 1.10 1.9 1.8 1.7; do
  if automake-${v} --version >/dev/null 2>&1; then
    amvers="-${v}"
    break
  fi
done
if test "${amvers}" = "no"; then
  automake --version > /dev/null 2>&1 && amvers=""
fi

#libtool# # Check for libtool
#libtool# libtoolize="no"
#libtool# if glibtoolize --version >/dev/null 2>&1; then
#libtool#   libtoolize="glibtoolize"
#libtool# elif libtoolize --version >/dev/null 2>&1; then
#libtool#   libtoolize="libtoolize"
#libtool# fi
#libtool#
#libtool# if test "$libtoolize" = "no"; then
#libtool#   set +x
#libtool#   echo "$0: you need libtool"
#libtool#   exit 1
#libtool#  fi

# Remove old cruft
rm -f aclocal.m4 configure config.guess config.log config.sub config.cache config.h.in config.h compile ltmain.sh libtool ltconfig missing mkinstalldirs depcomp install-sh
rm -Rf autom4te.cache
(cd autotools && rm -f config.guess config.sub missing mkinstalldirs compile ltmain.sh depcomp install-sh)

#libtool# ${libtoolize} --copy --force
#libtool#
#libtool# if test -f "ltmain.sh"; then
#libtool#   echo "$0: working around a minor libtool issue"
#libtool#   mv ltmain.sh autotools/
#libtool# fi

aclocal${amvers}
autoconf
autoheader
automake${amvers} --add-missing --copy

